version: "3.7"
services:
  laravel_8:
    build:
      args:
        user: joao
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: laravel-app
    command: supervisord -c /etc/supervisor/supervisord.conf
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    depends_on:
      - redis
    networks:
      - laravel-eti

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    networks:
      - laravel-eti
    depends_on:
      - laravel_8

  mysql:
    image: 'mysql:8.0'
    restart: unless-stopped
    volumes:
      - ./.docker/mysql/dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - '3307:3306'
    networks:
      - laravel-eti

  redis:
    image: redis:latest
    networks:
      - laravel-eti

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
    ports:
      - "9200:9200"
    networks:
      - laravel-eti
    deploy:
      resources:
        limits:
          memory: 3g
        reservations:
          memory: 2g

  logstash:
    image: docker.elastic.co/logstash/logstash:8.4.2
    container_name: logstash
    ports:
      - "5044:5044"
      - "9600:9600"
    volumes:
      - ./docker/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    depends_on:
      - elasticsearch
    networks:
      - laravel-eti

  kibana:
    image: docker.elastic.co/kibana/kibana:8.4.2
    container_name: kibana
    environment:
      - ELASTICSEARCH_PASSWORD=changeme
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - laravel-eti

volumes:
  esdata:
    driver: local

networks:
  laravel-eti:
    driver: bridge
